lec:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: lec-small-program
    username: root
    password: zaqzse1234
  redis:
    host: localhost
    port: 6379
    password: zaqzse1234
    database: 10
