lec:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: lec-small-program
    username: root
    password: zaqzse1234
#  alioss:
#    endpoint:
#    accessKeyId:
#    access-key-secret:
#    bucketName:
  redis:
    host: localhost
    port: 6379
    password: zaqzse1234
    database: 10
  wechat:
    appid: wx3404de74fac36c4d
    secret: c5658422ff4a79312756a8cfe0410aad
