lec:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: lec-small-program
    username: root
    password: zaqzse1234
#  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    accessKeyId: LTAI5tQwKPvL59H7ypHDbkr8
#    access-key-secret: 4V6R4K89px6Np3n576sewVtaioCyRk
#    bucketName: sky-take-out-core
  redis:
    host: localhost
    port: 6379
    password: zaqzse1234
    database: 10
  wechat:
    appid: wx3404de74fac36c4d
    secret: c5658422ff4a79312756a8cfe0410aad
